[platformio]
default_envs = sensor_test

[env]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
lib_deps =
    Servo
    arkhipenko/TaskScheduler
    adafruit/Adafruit BNO055
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    adafruit/Adafruit TCS34725
    https://github.com/bitcraze/Bitcraze_PMW3901.git
    https://github.com/DFRobot/DFRobot_MatrixLidar.git
    https://github.com/sparkfun/SparkFun_SX1509_Arduino_Library.git
    pololu/VL53L1X@^1.3.1
    pololu/VL53L0X@^1.3.1
    https://github.com/cesarvandevelde/HerkulexServo.git
    https://github.com/rlogiacco/CircularBuffer.git

[env:sensor_test]
extends = env
build_flags = -DROBOT_MODE=3
build_src_filter =
    -<*>
    +<main.cpp>
    +<filter_positionData.cpp>
    +<hd_raw_encoder.cpp>
    +<hd_move_motors.cpp>
    +<hd_move_servoArm.cpp>
    +<hd_move_smartServos.cpp>
    +<hd_raw_bluetooth.cpp>
    +<hd_raw_imu.cpp>
    +<hd_raw_inductiveProximity.cpp>
    +<hd_raw_tof.cpp>
    +<hd_raw_tof8x8.cpp>
    +<hd_raw_limitSwitch.cpp>
    +<hd_raw_ultrasonic.cpp>
    +<hd_raw_xy.cpp>
    +<filter_weightDetect.cpp>
    +<logic_weightCollection.cpp>
    +<logic_weightHunting.cpp>
    +<logic_weightHandling.cpp>
    +<logic_wallAvoidance.cpp>

[env:motion_test]
extends = env
build_flags = -DROBOT_MODE=1

[env:claw_test]
extends = env
build_flags = -DROBOT_MODE=2

[env:sensor_claw_test]
extends = env
build_flags = -DROBOT_MODE=4

[env:nav_motion_test]
extends = env
build_flags = -DROBOT_MODE=5

[env:full_integration_test]
extends = env
build_flags = -DROBOT_MODE=6

[env:competition]
extends = env
build_flags = -DROBOT_MODE=7
