[env:teensy40]
platform = teensy
board = teensy40
framework = arduino

; Match whatever baud rate you're actually using in code —
; the template currently sets BAUD_RATE 9600, but you may want to
; change that #define to 115200 to match your other test projects.
monitor_speed = 115200

lib_deps =
    arkhipenko/TaskScheduler
    adafruit/Adafruit TCS34725
    adafruit/Adafruit BusIO
    https://github.com/sparkfun/SparkFun_SX1509_Arduino_Library.git
    pololu/VL53L1X@^1.3.1
    pololu/VL53L0X
    https://github.com/bitcraze/Bitcraze_PMW3901.git
    https://github.com/cesarvandevelde/HerkulexServo.git
    https://github.com/rlogiacco/CircularBuffer.git
    adafruit/Adafruit BNO055
    adafruit/Adafruit Unified Sensor

